apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux-rollback-agent
  namespace: flux-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flux-rollback-agent
  template:
    metadata:
      labels:
        app: flux-rollback-agent
    spec:
      securityContext:
        fsGroup: 10001
        runAsNonRoot: true
        supplementalGroups:
        - 10001
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: flux-rollback-agent
      containers:
        - name: agent
          image: ghcr.io/eumel8/rollback-controller:latest
          env:
            - name: REVERT_MODE
              value: "echo"
            - name: DEBOUNCE_SECONDS
              value: "10"
            - name: GITLAB_TOKEN
              value: "123"
            - name: GITLAB_PROJECT_ID
              value: "123"
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 10m
              memory: 24Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
              - CAP_NET_RAW
            privileged: false
            readOnlyRootFilesystem: true
            runAsUser: 10001
            runAsGroup: 10001
            seccompProfile:
              type: RuntimeDefault
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flux-rollback-agent
  namespace: flux-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flux-rollback-agent
rules:
  - apiGroups: ["helm.toolkit.fluxcd.io"]
    resources: ["helmreleases"]
    verbs: ["get","list","watch"]
  - apiGroups: ["kustomize.toolkit.fluxcd.io"]
    resources: ["kustomizations"]
    verbs: ["get","list","watch"]
  - apiGroups: ["source.toolkit.fluxcd.io"]
    resources: ["gitrepositories"]
    verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flux-rollback-agent
subjects:
  - kind: ServiceAccount
    name: flux-rollback-agent
    namespace: flux-system
roleRef:
  kind: ClusterRole
  name: flux-rollback-agent
  apiGroup: rbac.authorization.k8s.io
