apiVersion: toolkit.fluxcd.io/v1alpha1
kind: RollbackPolicy
metadata:
  name: flux-revert-policy
  namespace: flux-system
spec:
  targets:
    - kind: Kustomization
      name: my-app
      namespace: flux-system
    - kind: HelmRelease
      name: my-app
      namespace: flux-system
  debounceSeconds: 300
  gitlabProjectID: 123
  gitlabTokenSecret: gitlab-token
  revertBranchPrefix: revert
