---
apiVersion: v1
kind: Namespace
metadata:
  name: my-app
spec:
  finalizers:
  - kubernetes
---
apiVersion: toolkit.fluxcd.io/v1alpha1
kind: RollbackPolicy
metadata:
  name: flux-revert-policy
  namespace: my-app
spec:
  targets:
    - kind: Kustomization
      name: my-app
      namespace: my-app
    - kind: HelmRelease
      name: my-app
      namespace: my-app
  debounceSeconds: 30
  gitlabProjectID: 123
  gitlabTokenSecret: gitlab-token
  revertBranchPrefix: revert
