name: Helm Lint, Package, Push

permissions:
  contents: read
  packages: write

on: 
  push: 
    paths: 
    - 'test/charts/my-app/**'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Helm lint & package & push
        run: |
          helm version
          helm registry login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
          cd test/charts/my-app
          helm lint .
          helm package .
          helm push $(ls *.tgz| head -1) oci://ghcr.io/${{ github.actor }}/charts
